### ISSUE TITLE
MSET9 Broke 3DS: Now It’s US and Outdated!

### ISSUE THREAD

**Issue by ghost** [zoogie/MSET9#46]
**Device:** Nintendo New 3DS LL (Japan)
**System Version Before Process:** 11.17.0-50J (Japanese version)
**System Version After Process:** 11.5.0-38U (US version)
**Firmware Issue:** The region and firmware version changed unexpectedly, and the new version is outdated.

**Guide Link Used:** https://3ds.hacks.guide/installing-boot9strap-(mset9-cli).html

Steps to Reproduce:
1. I followed the instructions to install Boot9Strap on New 3DS LL.
2. I followed each step carefully and did not encounter any errors during the process.
3. After completing the installation, the New 3DS LL rebooted, but it displayed a different system version 11.5.0-38U rather than the original 11.17.0-50J.
4. The region was also switched to “US,” and I lost access to the original Japanese firmware.
5. Additionally, I now have **two “System Settings” icons** on the HOME Menu, which appear to be duplicates.

**Comment by Anonymous941** [comment]
That's bizarre, and I doubt it was caused by MSET9.
An already existing emuNAND might cause this, if that's the issue then rebooting without an SD card inserted should fix it.

Otherwise you can look at https://3ds.hacks.guide/region-changing.html and use the Japanese version.  This uses CTRTransfer which will reset your firmware back to Japanese

**Comment by ghost** [comment]
> That's bizarre, and I doubt it was caused by MSET9. An already existing emuNAND might cause this, if that's the issue then rebooting without an SD card inserted should fix it.
> 

I tried rebooting without the SD card inserted, but unfortunately, it didn’t solve the issue. 

> Otherwise you can look at https://3ds.hacks.guide/region-changing.html and use the Japanese version. This uses CTRTransfer which will reset your firmware back to Japanese

I used the Japanese CTRTransfer images from the guide, but only 11.15.0-47J is available. It restored the JP region, but I’m still on 11.15J, not 11.17J
Is there a safe way to update to 11.17J afterward?

System update via Internet through the official Nintendo servers in System Settings doesn’t work. It constantly searches for updates but does not download them and after a few minutes an error message always appears.

**Comment by Anonymous941** [comment]
> Is there a safe way to update to 11.17J afterward?

Normally just running system update is safe with Luma3DS installed.  But for some reason that isn't working, so you can try updating in recovery mode by shutting down, then holding A+L+R+D-pad up as you press power.  A system update screen should show up and let you update.

**Comment by ghost** [comment]
> > Is there a safe way to update to 11.17J afterward?
> 
> Normally just running system update is safe with Luma3DS installed. But for some reason that isn't working, so you can try updating in recovery mode by shutting down, then holding A+L+R+D-pad up as you press power. A system update screen should show up and let you update.

Not working in recovery mode. It constantly searches for updates but does not download anything and after a few minutes an error message appears automatically.

Is there another way without a safe way?

**Comment by Anonymous941** [comment]
> Not working in recovery mode. It constantly searches for updates but does not download anything and after a few minutes an error message appears automatically.

That's so strange.  I've never heard of this happening before, especially after a CTRTransfer.  Maybe there are connection issues?

Edit: I just read that Pretendo can cause issues with system updates.  If you have Pretendo installed then if you open Nimbus, choose Nintendo, then try the update again, that might fix this.

> Is there another way without a safe way?

I'm not sure what you mean, are you asking if there's a safe way to upgrade?  Since the online update isn't working for some reason, you can try an offline update.

First of all, make sure to [make a NAND backup](https://3ds.hacks.guide/godmode9-usage.html#creating-a-nand-backup) if you haven't already in case things get worse.  As long as you have the NAND backup, you don't really have to worry about bricks since you can always restore from the backup.

To do an offline update, download [sysUpdater](https://github.com/profi200/sysUpdater) and download the 11.17.0-50J update zip from the [3DS firmware archive](https://darthsternie.net/3ds-firmwares/).  Then make a folder called "updates" (without quotes) on your SD card, and extract the update zip into there.  That folder should then have a bunch of cia files.  After that, just run sysUpdater and it should hopefully update you to the right firmware version.

Also I'm very confused how your 3DS got in this situation in the first place, since firmware regions shouldn't switch like this...

**Comment by ghost** [comment]
> > Not working in recovery mode. It constantly searches for updates but does not download anything and after a few minutes an error message appears automatically.
> 
> That's so strange. I've never heard of this happening before, especially after a CTRTransfer. Maybe there are connection issues?
> 
> Edit: I just read that Pretendo can cause issues with system updates. If you have Pretendo installed then if you open Nimbus, choose Nintendo, then try the update again, that might fix this.
> 

There were no connection problems. But Nintendo eShop isn't working either. Pretendo not installed.

> > Is there another way without a safe way?
> 
> I'm not sure what you mean, are you asking if there's a safe way to upgrade? Since the online update isn't working for some reason, you can try an offline update.
> 
> First of all, make sure to [make a NAND backup](https://3ds.hacks.guide/godmode9-usage.html#creating-a-nand-backup) if you haven't already in case things get worse. As long as you have the NAND backup, you don't really have to worry about bricks since you can always restore from the backup.
> 
> To do an offline update, download [sysUpdater](https://github.com/profi200/sysUpdater) and download the 11.17.0-50J update zip from the [3DS firmware archive](https://darthsternie.net/3ds-firmwares/). Then make a folder called "updates" (without quotes) on your SD card, and extract the update zip into there. That folder should then have a bunch of cia files. After that, just run sysUpdater and it should hopefully update you to the right firmware version.
> 
> Also I'm very confused how your 3DS got in this situation in the first place, since firmware regions shouldn't switch like this...

It's a Nintendo New 3DS LL and I didn't buy it new online. Thanks to the sysUpdater guide, it now works. The 11.17.0-50J firmware is now fully restored. The system update search and Nintendo eShop are also working again. Thank you.

**Comment by Anonymous941** [comment]
> It's a Nintendo New 3DS LL and I didn't buy it new online.

Okay, that explains it, the previous owner must have used CTRTransfer and messed with the updating somehow.

> Thanks to the sysUpdater guide, it now works. The 11.17.0-50J firmware is now fully restored. The system update search and Nintendo eShop are also working again. Thank you.

I'm glad it finally worked!
